;; CONFIG TEMPLATE
;; Enter values for your PVE and PBS instances. Refer to README on where to find these values

[PVE]
user = 
ip = 
pve_token_name = 
pve_token_value = 
verify_ssl = False

[PBS]
user = 
ip = 
pbs_token_name = 
pbs_token_value = 
service = pbs
verify_ssl = False